# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-19 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cron',
            name='hosts_list',
        ),
        migrations.AddField(
            model_name='cron',
            name='hosts_list',
            field=models.ManyToManyField(to='web.Host', verbose_name='执行机器'),
        ),
    ]
